# Generated by Django 5.2.15 on 2026-06-26 16:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='StudShiny', max_length=120)),
                ('direccion', models.CharField(blank=True, default='Bogota, Colombia', max_length=160)),
                ('telefono', models.CharField(blank=True, default='+57 302 764 10 35', max_length=40)),
                ('correo', models.EmailField(blank=True, default='contacto@studshiny.com', max_length=254)),
                ('horario', models.CharField(blank=True, default='Lunes a sabado, 10:00 a.m. a 7:00 p.m.', max_length=160)),
                ('mensaje_cuidados', models.TextField(default='Lava la zona con solucion salina, evita tocar la perforacion y consulta al estudio ante molestias.')),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.CharField(max_length=255)),
                ('visible', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.CharField(max_length=60)),
                ('material', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=40)),
                ('calibre', models.CharField(blank=True, max_length=40)),
                ('medida', models.CharField(blank=True, max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=5)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.CharField(blank=True, max_length=255)),
                ('en_promocion', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADO', 'Agotado')], default='DISPONIBLE', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['precio'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=140)),
                ('tipo_documento', models.CharField(choices=[('Cedula de ciudadania', 'Cedula de ciudadania'), ('Permiso especial de permanencia', 'Permiso especial de permanencia'), ('Pasaporte', 'Pasaporte')], max_length=60)),
                ('numero_documento', models.CharField(max_length=40, unique=True)),
                ('edad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(14)])),
                ('tipo_sangre', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=30)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=120)),
                ('tipo_perforacion_interes', models.CharField(blank=True, max_length=80)),
                ('alergias_patologias', models.TextField(blank=True)),
                ('numero_perforaciones', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=140)),
                ('telefono_cliente', models.CharField(blank=True, max_length=30)),
                ('tipo_perforacion', models.CharField(max_length=100)),
                ('fecha_cita', models.DateTimeField()),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='SOLICITADA', max_length=20)),
                ('estado_pago', models.BooleanField(default=False)),
                ('notas_cuidados', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente')),
                ('joya_utilizada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimientos', to='core.producto')),
                ('materiales_medicos', models.ManyToManyField(blank=True, related_name='procedimientos_insumo', to='core.producto')),
            ],
            options={
                'ordering': ['-fecha_cita'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('PSE', 'PSE'), ('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta')], default='PSE', max_length=40)),
                ('pagada', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente')),
                ('procedimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.procedimiento')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
